# Generated by Django 5.2.17 on 2026-10-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_public_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCache",
            fields=[
                (
                    "key",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="HolidayOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("provisional", "Provisional"),
                        ],
                        default="confirmed",
                        max_length=12,
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hide the library holidays of this country on this date",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the correction comes from, e.g. an official announcement",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("country", "date")},
            },
        ),
    ]
