"""Settings registry.

Single source of truth for every configurable setting: validation, defaults, permission to edit,
UI help text, and docs/SETTINGS_REFERENCE.md (generated by `manage.py settings_reference`).
"""
from __future__ import annotations

import re
import zoneinfo
from dataclasses import dataclass, field
from typing import Any, Callable

GLOBAL, USER = "global", "user"
MAIN_ADMIN, SELF = "main_admin", "self"


class SettingError(ValueError):
    pass


@dataclass(frozen=True)
class SettingDef:
    key: str
    label: str
    description: str
    type: str  # bool|int|str|choice|int_list|time|secret|email|url|timezone|path|channel_list
    default: Any
    section: str
    scope: str = GLOBAL
    editable_by: str = MAIN_ADMIN
    choices: tuple = ()
    min: int | None = None
    max: int | None = None
    depends_on: tuple[str, ...] = ()
    effect: str = ""
    restart: bool = False
    help: str = ""  # guide-slug#anchor
    example: str = ""
    validator: Callable[[Any], None] | None = field(default=None, compare=False)

    @property
    def secret(self) -> bool:
        return self.type == "secret"

    def public(self) -> dict:
        return {
            "key": self.key,
            "label": self.label,
            "description": self.description,
            "type": self.type,
            "default": None if self.secret else self.default,
            "section": self.section,
            "scope": self.scope,
            "editable_by": self.editable_by,
            "choices": list(self.choices),
            "min": self.min,
            "max": self.max,
            "depends_on": list(self.depends_on),
            "effect": self.effect,
            "restart": self.restart,
            "help": self.help,
            "example": self.example,
            "secret": self.secret,
        }


CHANNELS = ("in_app", "email", "telegram")
THEMES = ("green", "blue", "mono")
LAYOUTS = ("three_panel", "full_page")


def _validate_thresholds(value):
    if len(value) == 0:
        raise SettingError("Choose at least one reminder day.")
    if len(set(value)) != len(value):
        raise SettingError("Reminder days must be unique.")
    for v in value:
        if v < 0 or v > 730:
            raise SettingError("Reminder days must be between 0 and 730.")


def _validate_template(value: str):
    if ".." in value or value.startswith("/") or "\\" in value:
        raise SettingError("Templates cannot contain '..', '\\' or start with '/'.")
    allowed = {"owner", "type", "title", "year", "month", "version_id", "document_id", "original_name"}
    for name in re.findall(r"{([^}]*)}", value):
        if name not in allowed:
            raise SettingError(f"Unknown placeholder {{{name}}}. Allowed: {', '.join(sorted(allowed))}.")
    if "{version_id}" not in value:
        raise SettingError("Template must include {version_id} so files never collide.")


DEFAULT_MEMBER_TEMPLATE = "\n".join([
    "Identity/Passport", "Identity/Visa & Residence", "Identity/National ID", "Education", "Medical", "Travel",
    "Banking & Finance", "Insurance", "Vehicle", "House & Property", "Certificates",
])


def template_lines(value: str) -> list[list[str]]:
    paths = []
    for raw in (value or "").splitlines():
        line = raw.strip().strip("/")
        if not line:
            continue
        parts = [p.strip() for p in line.split("/") if p.strip()]
        paths.append(parts)
    return paths


def _validate_folder_template(value: str):
    paths = template_lines(value)
    if len(paths) > 100:
        raise SettingError("Use at most 100 template folders.")
    for parts in paths:
        if len(parts) > 8:
            raise SettingError(f"'{'/'.join(parts)}' is nested too deeply (at most 8 levels).")
        for part in parts:
            if part in (".", "..") or "\\" in part or len(part) > 200:
                raise SettingError(f"'{part}' is not a valid folder name.")


SETTINGS: list[SettingDef] = [
    # ---- General
    SettingDef("general.app_name", "Application name", "Name shown in the header, browser tab and notifications.",
               "str", "Personal Documents", "general", max=60, effect="Changes the visible name immediately.",
               help="settings#general"),
    SettingDef("general.timezone", "Installation timezone",
               "Timezone used for expiry calculations, reminder send time and date display.",
               "timezone", "Asia/Riyadh", "general",
               effect="Reminder day boundaries and send time follow this timezone from the next scheduler run.",
               help="expiry-rules#timezone", example="Asia/Riyadh"),
    SettingDef("general.date_format", "Date display", "How dates are displayed throughout the app.",
               "choice", "d MMM yyyy", "general", choices=("d MMM yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "MM/dd/yyyy"),
               effect="Display only; stored values are unaffected.", help="settings#general"),
    SettingDef("general.installation_id", "Installation identity",
               "Label identifying this installation in backups and diagnostics.", "str", "personaldocs",
               "general", max=60, effect="Used in backup folder names and diagnostics.", help="backup-restore#identity"),
    # ---- Documents & folders
    SettingDef("documents.filename_template", "Stored filename template",
               "Managed path used for newly uploaded originals, relative to the storage folder. Existing files are not renamed.",
               "str", "{owner}/{year}/{title}--{version_id}", "documents", max=200,
               effect="Applies to new uploads only; existing originals keep their path.",
               help="originals-versions#naming", example="{owner}/{type}/{title}--{version_id}",
               validator=_validate_template),
    SettingDef("documents.max_upload_mb", "Maximum upload size (MB)", "Largest single file accepted.", "int", 512,
               "documents", min=1, max=10240, effect="Larger uploads are rejected before storage.",
               help="folder-imports#limits", example="512"),
    SettingDef("documents.blocked_extensions", "Blocked extensions",
               "Comma separated extensions that are refused at upload (they would never execute anyway).",
               "str", "", "documents", effect="Refuses matching uploads.", help="office-dicom#formats", example="exe,bat"),
    SettingDef("documents.emoji_suggestions", "Suggest folder emoji",
               "Suggest an emoji from the folder name (Travel ✈️, Passport 🛂 …) when folders are created.",
               "bool", True, "documents", effect="New folders get a suggested emoji; existing overrides stay.",
               help="folder-imports#emoji"),
    SettingDef("documents.member_template", "Folder template for new members",
               "Optional folders (one path per line, use / for sub-folders) offered when adding a person or applied to an existing folder. Nothing is created unless you choose to apply it.",
               "str", DEFAULT_MEMBER_TEMPLATE, "documents", max=4000, validator=_validate_folder_template,
               effect="Used the next time a template is applied; existing folders are never removed or renamed.",
               help="folder-imports#templates", example="Identity/Passport"),
    SettingDef("documents.import_roots", "Approved server import folders",
               "Server/NAS paths (one per line) from which the main administrator may import. Sources are copied, never modified.",
               "str", "", "documents", effect="Only listed folders can be scanned by the server import wizard.",
               help="folder-imports#server", example="/mnt/nas/old-documents"),
    # ---- Processing
    SettingDef("processing.ocr_enabled", "Local OCR", "Run local English OCR (Tesseract) on scans and images.",
               "bool", True, "processing", effect="When off, scans are stored and previewed but not text-searchable.",
               help="ocr-corrections#ocr"),
    SettingDef("processing.ocr_language", "OCR language", "Tesseract language pack used.", "choice", "eng",
               "processing", choices=("eng",), effect="Only English is supported in the initial release.",
               help="ocr-corrections#ocr"),
    SettingDef("processing.heavy_concurrency", "Concurrent OCR/conversion jobs",
               "How many expensive jobs run at once. 1 is recommended for 2 vCPU / 4 GB.", "int", 1, "processing",
               min=1, max=8, effect="Higher values use more CPU and memory; takes effect when the worker restarts.",
               restart=True, help="ocr-corrections#limits", example="1"),
    SettingDef("processing.timeout_seconds", "Processing timeout (seconds)",
               "Maximum time for one OCR or conversion step.", "int", 600, "processing", min=30, max=7200,
               effect="Jobs exceeding this fail with a timeout error and can be retried.", help="ocr-corrections#limits"),
    SettingDef("processing.max_pages", "Maximum pages for OCR", "PDFs above this page count are stored without OCR.",
               "int", 300, "processing", min=1, max=5000, effect="Protects the server from very large scans.",
               help="ocr-corrections#limits"),
    SettingDef("processing.max_image_megapixels", "Maximum image size (megapixels)",
               "Images above this are refused for processing (decompression bomb protection).", "int", 120,
               "processing", min=1, max=1000, effect="Larger images are stored but not processed.",
               help="ocr-corrections#limits"),
    # ---- Notifications
    SettingDef("notifications.expiry_days", "Expiry reminder days",
               "Days before expiry when reminders are sent. 0 means on the expiry day. Reminders stop after the expiry day.",
               "int_list", [90, 60, 30, 7, 0], "notifications",
               effect="Applies from the next scheduler run; already-passed thresholds are not re-sent.",
               help="expiry-rules#schedule", example="90 means notify 90 days before expiry",
               validator=_validate_thresholds),
    SettingDef("notifications.send_time", "Reminder send time", "Local time of day reminders are sent.",
               "time", "08:00", "notifications", effect="Next run uses the new time.", help="expiry-rules#schedule",
               example="08:00"),
    SettingDef("notifications.notify_owner", "Notify document owner", "Owner receives expiry reminders.",
               "bool", True, "notifications", effect="Disabling stops owner reminders.", help="expiry-rules#recipients"),
    SettingDef("notifications.notify_head", "Notify head of family", "The owner's designated family head receives reminders.",
               "bool", True, "notifications", effect="Disabling stops head reminders.", help="expiry-rules#recipients"),
    SettingDef("notifications.default_channels", "Default channels",
               "Channels enabled for users who have not chosen their own.", "channel_list", ["in_app", "email"],
               "notifications", effect="Affects users without personal preferences.", help="expiry-rules#channels"),
    SettingDef("notifications.required_channels", "Required channels",
               "Channels users cannot turn off. In-app is always on.", "channel_list", ["in_app"], "notifications",
               effect="Users see these channels locked on; missing contact details are flagged.",
               help="expiry-rules#channels"),
    # ---- Connections
    SettingDef("smtp.enabled", "Email (SMTP) enabled", "Send notification and password-reset email.", "bool", False,
               "connections", depends_on=("smtp.host", "smtp.from_address"),
               effect="When off, no email is sent and email channels show 'not configured'.", help="smtp#setup"),
    SettingDef("smtp.host", "SMTP host", "Mail server hostname.", "str", "", "connections", max=200, help="smtp#setup",
               example="smtp.example.com"),
    SettingDef("smtp.port", "SMTP port", "Mail server port.", "int", 587, "connections", min=1, max=65535,
               help="smtp#setup"),
    SettingDef("smtp.security", "SMTP security", "Connection security.", "choice", "starttls", "connections",
               choices=("starttls", "ssl", "none"), help="smtp#setup"),
    SettingDef("smtp.username", "SMTP username", "Login name for the mail server (optional).", "str", "",
               "connections", max=200, help="smtp#setup"),
    SettingDef("smtp.password", "SMTP password", "Stored encrypted. Leave empty to keep the current value.",
               "secret", "", "connections", help="smtp#setup"),
    SettingDef("smtp.from_address", "From address", "Sender address for outgoing email.", "email", "",
               "connections", help="smtp#setup", example="documents@example.com"),
    SettingDef("telegram.enabled", "Telegram enabled", "Send notifications through your Telegram bot.", "bool", False,
               "connections", depends_on=("telegram.bot_token",), effect="When off, Telegram channels are unavailable.",
               help="telegram#setup"),
    SettingDef("telegram.bot_token", "Telegram bot token", "Token from @BotFather. Stored encrypted.", "secret", "",
               "connections", help="telegram#setup"),
    SettingDef("telegram.bot_username", "Telegram bot username", "Used to build the link shown to users.", "str", "",
               "connections", max=64, help="telegram#setup", example="MyFamilyDocsBot"),
    SettingDef("whatsapp.status", "WhatsApp", "Personal WhatsApp notifications are a later-phase feature.", "choice",
               "planned", "connections", choices=("planned",), effect="Not available in this release.",
               help="settings#future"),
    # ---- Authentication
    SettingDef("auth.session_days", "Session length (days)", "How long a 'Remember me' sign-in lasts.", "int", 14,
               "authentication", min=1, max=90, effect="Applies to new sign-ins.", help="totp-recovery#sessions"),
    SettingDef("auth.reset_token_minutes", "Password reset link lifetime (minutes)",
               "How long an emailed reset link remains valid.", "int", 30, "authentication", min=5, max=1440,
               help="totp-recovery#reset"),
    SettingDef("auth.login_rate_limit", "Failed sign-ins before delay",
               "Failed attempts per account/IP within 15 minutes before further attempts are refused.", "int", 8,
               "authentication", min=3, max=100, help="totp-recovery#sessions"),
    SettingDef("google.enabled", "Google sign-in enabled",
               "Allow linked Google accounts to sign in. Disabled until client ID and secret are configured.", "bool",
               False, "authentication", depends_on=("google.client_id", "google.client_secret"),
               effect="Disabling blocks new Google sign-ins immediately; existing sessions continue until they expire or are signed out.",
               help="google#enable"),
    SettingDef("google.client_id", "Google OAuth client ID", "Web application client ID from Google Cloud Console.",
               "str", "", "authentication", max=200, help="google#credentials"),
    SettingDef("google.client_secret", "Google OAuth client secret", "Stored encrypted and never shown again.",
               "secret", "", "authentication", help="google#credentials"),
    # ---- Storage & backup
    SettingDef("backup.target", "Backup destination", "Mounted NAS/file-share path for backups.", "path", "",
               "storage", effect="Backups are refused when this path is not a mount point or lacks the marker file.",
               help="backup-restore#target", example="/mnt/nas-backup/personaldocs"),
    SettingDef("backup.require_mount", "Require mounted destination",
               "Refuse to back up unless the destination is a mount point (prevents filling the local disk).",
               "bool", True, "storage", help="backup-restore#target"),
    SettingDef("backup.schedule_time", "Daily backup time", "Local time for the automatic daily backup. Empty disables.",
               "time", "02:30", "storage", help="backup-restore#schedule", example="02:30"),
    SettingDef("backup.keep_daily", "Backups to keep", "Number of most recent successful backups retained (proposed default, not a user decision).",
               "int", 14, "storage", min=1, max=365, effect="Older backups beyond this count are pruned; the newest verified backup is never pruned.",
               help="backup-restore#retention"),
    SettingDef("backup.include_keys", "Include encryption key in backup",
               "Include the integration-secret encryption key so restores can decrypt SMTP/Telegram/email credentials. Protect the backup share accordingly.",
               "bool", True, "storage", help="backup-restore#keys"),
    SettingDef("audit.retention_days", "Audit log retention (days)", "Audit events older than this are deleted. 0 keeps forever.",
               "int", 730, "activity", min=0, max=36500, help="settings#activity"),
    # ---- AI (future)
    SettingDef("ai.status", "Local AI", "Local AI assistance is planned for a later release and is disabled.",
               "choice", "unavailable", "ai", choices=("unavailable",), effect="No AI features run.", help="settings#future"),
    # ---- Per-user
    SettingDef("me.theme", "Theme", "Colour theme for your account on every device.", "choice", "green", "appearance",
               scope=USER, editable_by=SELF, choices=THEMES, effect="Applies immediately on all your devices.",
               help="themes#choose"),
    SettingDef("me.layout", "Default document layout", "Three-panel browser or full-page viewer.", "choice",
               "three_panel", "appearance", scope=USER, editable_by=SELF, choices=LAYOUTS, help="themes#layout"),
    SettingDef("me.channels", "My notification channels", "Channels you want reminders on. Required channels stay on.",
               "channel_list", None, "my_notifications", scope=USER, editable_by=SELF, help="expiry-rules#channels"),
    SettingDef("me.event_alerts", "Other alerts by email/Telegram",
               "Also send access, import and (for administrators) backup and integrity alerts to your email/Telegram channels. They always appear in the in-app feed.",
               "bool", True, "my_notifications", scope=USER, editable_by=SELF, help="expiry-rules#other-alerts"),
    SettingDef("me.dashboard_widgets", "Dashboard widgets", "Statistics shown on your dashboard.", "str",
               "documents,members,expiring,storage", "appearance", scope=USER, editable_by=SELF, help="getting-started#dashboard"),
]

BY_KEY = {s.key: s for s in SETTINGS}


def coerce(defn: SettingDef, value: Any) -> Any:
    t = defn.type
    if value is None and t in ("channel_list",) and defn.scope == USER:
        return None
    if t == "bool":
        if not isinstance(value, bool):
            raise SettingError("Must be true or false.")
    elif t == "int":
        try:
            value = int(value)
        except (TypeError, ValueError):
            raise SettingError("Must be a whole number.")
        if defn.min is not None and value < defn.min:
            raise SettingError(f"Must be at least {defn.min}.")
        if defn.max is not None and value > defn.max:
            raise SettingError(f"Must be at most {defn.max}.")
    elif t in ("str", "secret", "path", "email", "url"):
        if not isinstance(value, str):
            raise SettingError("Must be text.")
        value = value.strip() if t != "secret" else value
        if defn.max is not None and len(value) > defn.max:
            raise SettingError(f"Must be at most {defn.max} characters.")
        if t == "email" and value and not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", value):
            raise SettingError("Enter a valid email address.")
        if t == "path" and value and not value.startswith("/"):
            raise SettingError("Enter an absolute path such as /mnt/nas-backup.")
    elif t == "choice":
        if value not in defn.choices:
            raise SettingError(f"Choose one of: {', '.join(defn.choices)}.")
    elif t == "int_list":
        if isinstance(value, str):
            value = [v for v in re.split(r"[,\s]+", value) if v]
        try:
            value = [int(v) for v in value]
        except (TypeError, ValueError):
            raise SettingError("Enter whole numbers separated by commas.")
    elif t == "channel_list":
        if not isinstance(value, list) or any(v not in CHANNELS for v in value):
            raise SettingError(f"Channels must be from: {', '.join(CHANNELS)}.")
        value = [c for c in CHANNELS if c in value]
    elif t == "time":
        if not isinstance(value, str) or (value and not re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", value)):
            raise SettingError("Use 24-hour HH:MM, for example 08:00.")
    elif t == "timezone":
        try:
            zoneinfo.ZoneInfo(value)
        except Exception:
            raise SettingError("Unknown timezone. Use a name like Asia/Riyadh.")
    if defn.validator:
        defn.validator(value)
    if t == "int_list":
        value = sorted(value, reverse=True)
    return value
