"""Settings registry.

Single source of truth for every configurable setting: validation, defaults, permission to edit,
UI help text, and docs/SETTINGS_REFERENCE.md (generated by `manage.py settings_reference`).
"""
from __future__ import annotations

import re
import zoneinfo
from dataclasses import dataclass, field
from typing import Any, Callable

from apps.notify.event_defs import DEFAULT_CRITICAL
from apps.notify.event_defs import EVENTS as NOTIFY_EVENTS

GLOBAL, USER = "global", "user"
MAIN_ADMIN, SELF, ADMIN = "main_admin", "self", "admin"  # ADMIN: main administrator or Administrator role


class SettingError(ValueError):
    pass


@dataclass(frozen=True)
class SettingDef:
    key: str
    label: str
    description: str
    type: str  # bool|int|str|choice|choice_list|country_list|overview_layout|int_list|time|secret|email|url|timezone|path|channel_list|widget_list|event_list|event_matrix|json
    default: Any
    section: str
    scope: str = GLOBAL
    editable_by: str = MAIN_ADMIN
    choices: tuple = ()
    min: int | None = None
    max: int | None = None
    depends_on: tuple[str, ...] = ()
    effect: str = ""
    restart: bool = False
    help: str = ""  # guide-slug#anchor
    example: str = ""
    validator: Callable[[Any], None] | None = field(default=None, compare=False)
    choice_labels: dict | None = field(default=None, compare=False)  # labels for choice / choice_list values

    @property
    def secret(self) -> bool:
        return self.type == "secret"

    def public(self) -> dict:
        return {
            "key": self.key,
            "label": self.label,
            "description": self.description,
            "type": self.type,
            "default": None if self.secret else self.default,
            "section": self.section,
            "scope": self.scope,
            "editable_by": self.editable_by,
            "choices": list(self.choices),
            "min": self.min,
            "max": self.max,
            "depends_on": list(self.depends_on),
            "effect": self.effect,
            "restart": self.restart,
            "help": self.help,
            "example": self.example,
            "secret": self.secret,
        }


CHANNELS = ("in_app", "email", "telegram", "push")
THEMES = ("green", "blue", "mono")
# Tesseract language packs offered for OCR (Debian package tesseract-ocr-<code>)
_OCR_LANGS = {
    "eng": "English", "ara": "Arabic", "hin": "Hindi (Devanagari)", "urd": "Urdu", "tel": "Telugu", "tam": "Tamil",
    "mal": "Malayalam", "kan": "Kannada", "ben": "Bengali", "mar": "Marathi", "guj": "Gujarati", "pan": "Punjabi",
    "fra": "French", "deu": "German", "spa": "Spanish", "fas": "Persian", "tur": "Turkish",
}
LAYOUTS = ("three_panel", "full_page")


# Overview widgets that actually exist (id -> label), in their default order.
WIDGETS = {
    "documents": "Documents (count)",
    "members": "Family members (count)",
    "expiring": "Expiring in 90 days (count)",
    "storage": "Storage used",
    "review": "Needs review (count)",
    "family": "Family library (member cards)",
    "saved_views": "Saved views",
    "recent": "Recent documents",
    "upcoming": "Upcoming expiries",
    "review_queue": "Review queue",
    "backup": "Backup status (administrators)",
    "date": "Today (Gregorian + Hijri date)",
    "weather": "Weather",
    "summary": "Documents summary",
    "calendar": "Month calendar with holidays",
    "holidays": "Upcoming holidays",
    "shared": "Shared with me",
    "activity": "Recent activity",
    "security": "Security Health (administrators)",
}
# What a new account sees first (existing accounts keep the widgets they chose).
DEFAULT_WIDGETS = ["date", "weather", "summary", "calendar", "holidays", "upcoming", "shared", "recent", "activity",
                   "review_queue", "backup", "security"]
STAT_WIDGETS = ("documents", "members", "expiring", "storage", "review")


def _validate_group_mapping(value):
    if value in (None, ""):
        return
    if not isinstance(value, dict) or len(value) > 50:
        raise SettingError("Map authentik group names to a role.")
    for group, role in value.items():
        if not isinstance(group, str) or not group.strip() or len(group) > 120:
            raise SettingError("Group names must be non-empty text.")
        if role not in ("member", "administrator"):
            raise SettingError("Groups can only map to the Member or Administrator role (never Main administrator).")


def normalize_widgets(value) -> list[str]:
    """Ordered, de-duplicated widget ids. Accepts the old comma-separated text, in which only the counters were
    chosen and every other section was always shown (kept so upgrades look the same)."""
    if isinstance(value, str):
        chosen = [v.strip() for v in value.split(",") if v.strip() in WIDGETS]
        chosen += ["review"] + [w for w in WIDGETS if w not in STAT_WIDGETS]
        value = chosen
    out: list[str] = []
    for v in value or []:
        if v in WIDGETS and v not in out:
            out.append(v)
    return out


def _validate_thresholds(value):
    if len(value) == 0:
        raise SettingError("Choose at least one reminder day.")
    if len(set(value)) != len(value):
        raise SettingError("Reminder days must be unique.")
    for v in value:
        if v < 0 or v > 730:
            raise SettingError("Reminder days must be between 0 and 730.")


_HOST_RX = re.compile(r"^(?=.{1,253}$)([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$|^\[?[0-9A-Fa-f:.]+\]?$")


def _validate_host(value: str):
    if value and not _HOST_RX.match(value):
        raise SettingError("Enter a hostname or IP address, e.g. 192.168.1.20 or nas.local.")


def _validate_share(value: str):
    if value and (not re.fullmatch(r"[A-Za-z0-9/_.\- $]{1,200}", value) or ".." in value.split("/")):
        raise SettingError("Use letters, numbers, spaces and / _ . - $ only.")


def _validate_subfolder(value: str):
    if value and (not re.fullmatch(r"[A-Za-z0-9_.\-]{1,100}", value) or value in (".", "..")):
        raise SettingError("Use a single folder name (letters, numbers, _ . -).")


def _validate_plain(value: str):
    if value and not re.fullmatch(r"[^\s,=\\'\"\x00-\x1f]{1,100}", value):
        raise SettingError("Spaces, commas, quotes, backslashes and '=' are not allowed.")


def _validate_version(value: str):
    if value and not re.fullmatch(r"[0-9](\.[0-9])?", value):
        raise SettingError("Enter a version such as 4.1 or 3.0.")


def _validate_template(value: str):
    if ".." in value or value.startswith("/") or "\\" in value:
        raise SettingError("Templates cannot contain '..', '\\' or start with '/'.")
    allowed = {"owner", "type", "title", "year", "month", "version_id", "document_id", "original_name"}
    for name in re.findall(r"{([^}]*)}", value):
        if name not in allowed:
            raise SettingError(f"Unknown placeholder {{{name}}}. Allowed: {', '.join(sorted(allowed))}.")
    if "{version_id}" not in value:
        raise SettingError("Template must include {version_id} so files never collide.")


DEFAULT_MEMBER_TEMPLATE = "\n".join([
    "Identity/Passport", "Identity/Visa & Residence", "Identity/National ID", "Education", "Medical", "Travel",
    "Banking & Finance", "Insurance", "Vehicle", "House & Property", "Certificates",
])


def template_lines(value: str) -> list[list[str]]:
    paths = []
    for raw in (value or "").splitlines():
        line = raw.strip().strip("/")
        if not line:
            continue
        parts = [p.strip() for p in line.split("/") if p.strip()]
        paths.append(parts)
    return paths


def _validate_folder_template(value: str):
    paths = template_lines(value)
    if len(paths) > 100:
        raise SettingError("Use at most 100 template folders.")
    for parts in paths:
        if len(parts) > 8:
            raise SettingError(f"'{'/'.join(parts)}' is nested too deeply (at most 8 levels).")
        for part in parts:
            if part in (".", "..") or "\\" in part or len(part) > 200:
                raise SettingError(f"'{part}' is not a valid folder name.")


SETTINGS: list[SettingDef] = [
    # ---- General
    SettingDef("general.app_name", "Application name", "Name shown in the header, browser tab and notifications.",
               "str", "Personal Documents Management System", "general", max=60, effect="Changes the visible name immediately.",
               help="settings#general"),
    SettingDef("general.timezone", "Installation timezone",
               "Timezone used for expiry calculations, reminder send time and date display.",
               "timezone", "Asia/Riyadh", "general",
               effect="Reminder day boundaries and send time follow this timezone from the next scheduler run.",
               help="expiry-rules#timezone", example="Asia/Riyadh"),
    SettingDef("general.date_format", "Date display", "How dates are displayed throughout the app.",
               "choice", "d MMM yyyy", "general", choices=("d MMM yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "MM/dd/yyyy"),
               effect="Display only; stored values are unaffected.", help="settings#general"),
    SettingDef("general.installation_id", "Installation identity",
               "Label identifying this installation in backups and diagnostics.", "str", "personaldocs",
               "general", max=60, effect="Used in backup folder names and diagnostics.", help="backup-restore#identity"),
    # ---- Documents & folders
    SettingDef("documents.filename_template", "Stored filename template",
               "Managed path used for newly uploaded originals, relative to the storage folder. Existing files are not renamed.",
               "str", "{owner}/{year}/{title}--{version_id}", "documents", max=200,
               effect="Applies to new uploads only; existing originals keep their path.",
               help="originals-versions#naming", example="{owner}/{type}/{title}--{version_id}",
               validator=_validate_template),
    SettingDef("documents.max_upload_mb", "Maximum upload size (MB)", "Largest single file accepted.", "int", 512,
               "documents", min=1, max=10240, effect="Larger uploads are rejected before storage.",
               help="folder-imports#limits", example="512"),
    SettingDef("documents.blocked_extensions", "Blocked extensions",
               "Comma separated extensions that are refused at upload (they would never execute anyway).",
               "str", "", "documents", effect="Refuses matching uploads.", help="office-dicom#formats", example="exe,bat"),
    SettingDef("documents.emoji_suggestions", "Suggest folder emoji",
               "Suggest an icon from the name (Travel ✈️, Passport 🛂 …) for folders created directly in a person's or the family area. Deeper sub-folders get the standard 📁 icon; anyone can choose another icon.",
               "bool", True, "documents", effect="New folders get a suggested emoji; existing overrides stay.",
               help="folder-imports#emoji"),
    SettingDef("documents.member_template", "Folder template for new members",
               "Optional folders (one path per line, use / for sub-folders) offered when adding a person or applied to an existing folder. Nothing is created unless you choose to apply it.",
               "str", DEFAULT_MEMBER_TEMPLATE, "documents", max=4000, validator=_validate_folder_template,
               effect="Used the next time a template is applied; existing folders are never removed or renamed.",
               help="folder-imports#templates", example="Identity/Passport"),
    SettingDef("documents.import_roots", "Approved server import folders",
               "Server/NAS paths (one per line) from which the main administrator may import. Sources are copied, never modified.",
               "str", "", "documents", effect="Only listed folders can be scanned by the server import wizard.",
               help="folder-imports#server", example="/mnt/nas/old-documents"),
    # ---- Processing
    SettingDef("processing.ocr_enabled", "Text recognition (OCR)",
               "Master switch for local OCR (Tesseract). Which documents are recognised is decided per document type below.",
               "bool", True, "processing", effect="When off, nothing is recognised; documents are still stored, previewed and searchable by their details.",
               help="ocr-corrections#selective"),
    SettingDef("processing.ocr_languages", "OCR languages offered",
               "Languages people can choose when running OCR. The installer installs the matching Tesseract language packs; the health check reports missing ones.",
               "choice_list", ["eng", "ara", "hin"], "processing", choices=tuple(_OCR_LANGS),
               choice_labels=_OCR_LANGS, effect="Run `sudo personaldocs repair` after adding a language to install its pack.",
               help="ocr-corrections#languages"),
    SettingDef("processing.ocr_untyped_mode", "OCR for documents without a type",
               "Disabled: never. Manual: only when someone runs OCR. Automatic: the primary file is recognised after upload.",
               "choice", "manual", "processing", choices=("disabled", "manual", "automatic"),
               choice_labels={"disabled": "Disabled", "manual": "Manual (recommended)", "automatic": "Automatic"},
               effect="Applies to new uploads and to the Run OCR button.", help="ocr-corrections#selective"),
    SettingDef("processing.ocr_untyped_ai_allowed", "Local AI for documents without a type",
               "Allow Local AI to read the recognised text of documents without a type (when Local AI is on).",
               "bool", False, "processing", effect="Off: Local AI never receives their text.", help="ocr-corrections#ai"),
    SettingDef("processing.ocr_paused", "Pause OCR queue",
               "Queued OCR jobs wait until the queue is resumed. Uploads, previews and search keep working.",
               "bool", False, "processing", effect="Resuming continues the waiting jobs in order.", help="ocr-corrections#limits"),
    SettingDef("processing.ocr_max_file_mb", "Maximum file size for OCR (MB)",
               "Files above this size are stored and previewed but cannot be sent to OCR.", "int", 50, "processing",
               min=1, max=2000, help="ocr-corrections#limits"),
    SettingDef("processing.ocr_queue_max", "Maximum queued OCR jobs",
               "New OCR requests are refused with a clear message while this many are waiting.", "int", 50, "processing",
               min=1, max=10000, help="ocr-corrections#limits"),
    SettingDef("processing.ocr_max_attempts", "OCR retries",
               "How many times a failed OCR job is attempted before it is marked Failed.", "int", 2, "processing",
               min=1, max=10, help="ocr-corrections#limits"),
    SettingDef("processing.heavy_concurrency", "Concurrent OCR/conversion jobs",
               "How many expensive jobs run at once. 1 is recommended for 2 vCPU / 4 GB.", "int", 1, "processing",
               min=1, max=8, effect="Higher values use more CPU and memory; takes effect when the worker restarts.",
               restart=True, help="ocr-corrections#limits", example="1"),
    SettingDef("processing.timeout_seconds", "Processing timeout (seconds)",
               "Maximum time for one OCR or conversion step.", "int", 600, "processing", min=30, max=7200,
               effect="Jobs exceeding this fail with a timeout error and can be retried.", help="ocr-corrections#limits"),
    SettingDef("processing.max_pages", "Maximum pages per OCR job", "OCR requests covering more pages than this are refused (choose a page range instead).",
               "int", 300, "processing", min=1, max=5000, effect="Protects the server from very large scans.",
               help="ocr-corrections#limits"),
    SettingDef("processing.max_image_megapixels", "Maximum image size (megapixels)",
               "Images above this are refused for processing (decompression bomb protection).", "int", 120,
               "processing", min=1, max=1000, effect="Larger images are stored but not processed.",
               help="ocr-corrections#limits"),
    # ---- Notifications
    SettingDef("notifications.expiry_days", "Expiry reminder days",
               "Days before expiry when reminders are sent. 0 means on the expiry day. Reminders stop after the expiry day.",
               "int_list", [90, 60, 30, 7, 0], "notifications",
               effect="Applies from the next scheduler run; already-passed thresholds are not re-sent.",
               help="expiry-rules#schedule", example="90 means notify 90 days before expiry",
               validator=_validate_thresholds),
    SettingDef("notifications.send_time", "Reminder send time", "Local time of day reminders are sent.",
               "time", "08:00", "notifications", effect="Next run uses the new time.", help="expiry-rules#schedule",
               example="08:00"),
    SettingDef("notifications.notify_owner", "Notify document owner", "Owner receives expiry reminders.",
               "bool", True, "notifications", effect="Disabling stops owner reminders.", help="expiry-rules#recipients"),
    SettingDef("notifications.notify_head", "Notify head of family", "The owner's designated family head receives reminders.",
               "bool", True, "notifications", effect="Disabling stops head reminders.", help="expiry-rules#recipients"),
    SettingDef("notifications.default_channels", "Default channels for expiry reminders",
               "Channels used for expiry reminders by people who have not chosen their own.", "channel_list", ["in_app", "email"],
               "notifications", effect="Affects people without personal preferences.", help="expiry-rules#channels"),
    SettingDef("notifications.required_channels", "Required channels for expiry reminders",
               "Channels people cannot turn off for expiry reminders. In-app is always on.", "channel_list", ["in_app"], "notifications",
               effect="People see these channels locked on; missing contact details are flagged.",
               help="expiry-rules#channels"),
    SettingDef("notifications.critical_events", "Critical notifications",
               "Events people cannot turn off. They always arrive in-app and on the critical channels below.",
               "event_list", list(DEFAULT_CRITICAL), "notifications", choices=list(NOTIFY_EVENTS),
               effect="Applies to the next notification; people see these locked on.", help="expiry-rules#critical"),
    SettingDef("notifications.critical_channels", "Channels for critical notifications",
               "Every critical notification is also sent on these channels. Missing email addresses or unlinked Telegram are flagged to the person and to you, never reported as sent.",
               "channel_list", ["in_app", "email", "telegram"], "notifications",
               effect="Applies to the next notification.", help="expiry-rules#critical"),
    SettingDef("notifications.include_names", "Include names in email/Telegram",
               "Show folder, document and file names in external messages (long numbers are always masked). Turn off to send only counts and a sign-in link.",
               "bool", True, "notifications", help="expiry-rules#templates"),
    SettingDef("notifications.include_document_number", "Include document numbers in email/Telegram",
               "Show a masked document number (last four characters) in email and Telegram expiry messages. Never shown in push notifications.",
               "bool", False, "notifications", effect="Applies to the next notification.", help="notifications#privacy"),
    SettingDef("notifications.push_enabled", "Push notifications (PWA)",
               "Let people receive notifications on their phone or computer through the installed app (Web Push). "
               "Needs the HTTPS address; only known push services (Apple, Google, Mozilla, Microsoft) are contacted.",
               "bool", True, "notifications", effect="When off, push is not offered and nothing is sent.", help="notifications#push"),
    SettingDef("notifications.repeat_cooldown_hours", "Repeat cooldown for recurring conditions",
               "A recurring condition (antivirus unavailable, storage nearly full, update failures …) is notified again only after this many hours. "
               "New critical events (malware found, failed backups) are always sent at once.",
               "int", 24, "notifications", min=1, max=168, help="notifications#noise"),
    # ---- Connections
    SettingDef("smtp.enabled", "Email (SMTP) enabled", "Send notification and password-reset email.", "bool", False,
               "connections", depends_on=("smtp.host", "smtp.from_address"),
               effect="When off, no email is sent and email channels show 'not configured'.", help="smtp#setup"),
    SettingDef("smtp.host", "SMTP host", "Mail server hostname.", "str", "", "connections", max=200, help="smtp#setup",
               example="smtp.example.com"),
    SettingDef("smtp.port", "SMTP port", "Mail server port.", "int", 587, "connections", min=1, max=65535,
               help="smtp#setup"),
    SettingDef("smtp.security", "SMTP security", "Connection security.", "choice", "starttls", "connections",
               choices=("starttls", "ssl", "none"), help="smtp#setup"),
    SettingDef("smtp.username", "SMTP username", "Login name for the mail server (optional).", "str", "",
               "connections", max=200, help="smtp#setup"),
    SettingDef("smtp.password", "SMTP password", "Stored encrypted. Leave empty to keep the current value.",
               "secret", "", "connections", help="smtp#setup"),
    SettingDef("smtp.from_address", "From address", "Sender address for outgoing email.", "email", "",
               "connections", help="smtp#setup", example="documents@example.com"),
    SettingDef("telegram.enabled", "Telegram enabled", "Send notifications through your Telegram bot.", "bool", False,
               "connections", depends_on=("telegram.bot_token",), effect="When off, Telegram channels are unavailable.",
               help="telegram#setup"),
    SettingDef("telegram.bot_token", "Telegram bot token", "Token from @BotFather. Stored encrypted.", "secret", "",
               "connections", help="telegram#setup"),
    SettingDef("telegram.bot_username", "Telegram bot username", "Used to build the link shown to users.", "str", "",
               "connections", max=64, help="telegram#setup", example="MyFamilyDocsBot"),
    SettingDef("whatsapp.status", "WhatsApp", "Personal WhatsApp notifications are a later-phase feature.", "choice",
               "planned", "connections", choices=("planned",), effect="Not available in this release.",
               help="settings#future"),
    # ---- Authentication
    SettingDef("auth.session_days", "Session length (days)", "How long a 'Remember me' sign-in lasts.", "int", 14,
               "authentication", min=1, max=90, effect="Applies to new sign-ins.", help="totp-recovery#sessions"),
    SettingDef("auth.reset_token_minutes", "Password reset link lifetime (minutes)",
               "How long an emailed reset link remains valid.", "int", 30, "authentication", min=5, max=1440,
               help="totp-recovery#reset"),
    SettingDef("auth.login_rate_limit", "Failed sign-ins before delay",
               "Failed attempts per account/IP within 15 minutes before further attempts are refused.", "int", 8,
               "authentication", min=3, max=100, help="totp-recovery#sessions"),
    SettingDef("auth.allow_totp", "Allow authenticator apps (TOTP)",
               "People may set up a standard authenticator app or password manager for one-time codes.",
               "bool", True, "authentication", effect="Turning it off only stops new set-ups; people who already use one keep it, so nobody is locked out.",
               help="totp-recovery#totp"),
    SettingDef("auth.allow_passkeys", "Allow passkeys",
               "People may register passkeys (phone, computer, password manager or security key) as a second step after the password.",
               "bool", True, "authentication", effect="Turning it off only stops new registrations; existing passkeys keep working until removed.",
               help="passkeys#enable"),
    SettingDef("auth.passkey_mode", "Passkey sign-in mode",
               "Passwordless: the sign-in page offers Sign in with Passkey before any password, and a passkey (verified with "
               "fingerprint, face or PIN) signs the person in on its own. Password + Passkey: passkeys are only used as the "
               "second step after the password.",
               "choice", "passwordless", "authentication", choices=("passwordless", "mfa"), depends_on=("auth.allow_passkeys",),
               effect="Switching to Password + Passkey stops passwordless sign-in immediately; everyone can still use their password. "
                      "The main administrator's password and recovery codes always keep working.",
               help="passkeys#passwordless"),
    SettingDef("auth.require_2fa", "Require two-step verification",
               "Who must use a second step (passkey or authenticator app). People without one are asked to set it up right after signing in.",
               "choice", "none", "authentication", choices=("none", "admins", "all"),
               effect="Nobody is locked out: they sign in with their password and are then guided to set up a passkey or authenticator app.",
               help="passkeys#policy"),
    SettingDef("auth.recent_auth_minutes", "Re-confirmation window (minutes)",
               "How long after confirming it's you (password or passkey) sensitive changes are allowed: passkeys, authenticator app, recovery codes, passwordless.",
               "int", 10, "authentication", min=2, max=60, help="passkeys#recent-auth"),
    SettingDef("google.enabled", "Google sign-in enabled",
               "Allow linked Google accounts to sign in. Disabled until client ID and secret are configured.", "bool",
               False, "authentication", depends_on=("google.client_id", "google.client_secret"),
               effect="Disabling blocks new Google sign-ins immediately; existing sessions continue until they expire or are signed out.",
               help="google#enable"),
    SettingDef("google.client_id", "Google OAuth client ID", "Web application client ID from Google Cloud Console.",
               "str", "", "authentication", max=200, help="google#credentials"),
    SettingDef("google.client_secret", "Google OAuth client secret", "Stored encrypted and never shown again.",
               "secret", "", "authentication", help="google#credentials"),
    # ---- Storage & backup
    SettingDef("nas.type", "NAS connection", "How the backup share is reached. 'Already mounted' means Proxmox (or you) mounted it into the container; NFS/SMB lets the app mount it.",
               "choice", "none", "storage", choices=("none", "nfs", "smb"),
               effect="Click 'Connect NAS' after changing. The share is mounted at /mnt/pdnas and used as the backup destination.",
               help="backup-restore#nas"),
    SettingDef("nas.server", "NAS server", "Hostname or IP address of the NAS.", "str", "", "storage", max=253,
               validator=_validate_host, help="backup-restore#nas", example="192.168.1.20"),
    SettingDef("nas.share", "Share / export", "NFS export path (e.g. /volume1/backups) or SMB share name (e.g. backups).", "str", "",
               "storage", max=200, validator=_validate_share, help="backup-restore#nas", example="/volume1/backups"),
    SettingDef("nas.subfolder", "Folder on the share", "Sub-folder used for this installation's backups (created if missing).",
               "str", "personaldocs", "storage", max=100, validator=_validate_subfolder, help="backup-restore#nas"),
    SettingDef("nas.username", "SMB username", "Account on the NAS (SMB only).", "str", "", "storage", max=100,
               validator=_validate_plain, help="backup-restore#nas"),
    SettingDef("nas.password", "SMB password", "Stored encrypted; written to a root-only credentials file when mounting.",
               "secret", "", "storage", help="backup-restore#nas"),
    SettingDef("nas.domain", "SMB domain/workgroup", "Optional (SMB only).", "str", "", "storage", max=100,
               validator=_validate_plain, help="backup-restore#nas"),
    SettingDef("nas.version", "Protocol version", "NFS version (3, 4, 4.1) or SMB dialect (3.0, 2.1).", "str", "", "storage",
               max=10, validator=_validate_version, help="backup-restore#nas", example="4.1"),
    SettingDef("backup.target", "Backup destination", "Mounted NAS/file-share path for backups.", "path", "",
               "storage", effect="Backups are refused when this path is not a mount point or lacks the marker file.",
               help="backup-restore#target", example="/mnt/nas-backup/personaldocs"),
    SettingDef("backup.require_mount", "Require mounted destination",
               "Refuse to back up unless the destination is a mount point (prevents filling the local disk).",
               "bool", True, "storage", help="backup-restore#target"),
    SettingDef("backup.enabled", "Automatic backups", "Run backups automatically on the schedule below. Back up now always works.",
               "bool", True, "storage", help="backup-restore#schedule"),
    SettingDef("backup.frequency", "Backup frequency", "Daily, weekly (choose the day) or monthly (choose the day of the month).",
               "choice", "daily", "storage", choices=("daily", "weekly", "monthly"), depends_on=("backup.enabled",),
               effect="The next run is shown in Backup status.", help="backup-restore#schedule"),
    SettingDef("backup.schedule_time", "Backup time", "Local time of the automatic backup (installation timezone).",
               "time", "02:30", "storage", depends_on=("backup.enabled",), help="backup-restore#schedule", example="02:30"),
    SettingDef("backup.weekday", "Day of the week", "Used when the frequency is weekly.", "choice", "sun", "storage",
               choices=("mon", "tue", "wed", "thu", "fri", "sat", "sun"), depends_on=("backup.frequency",), help="backup-restore#schedule"),
    SettingDef("backup.month_day", "Day of the month", "Used when the frequency is monthly. 29–31 run on the last day of shorter months.",
               "int", 1, "storage", min=1, max=31, depends_on=("backup.frequency",), help="backup-restore#schedule", example="1"),
    SettingDef("backup.keep_daily", "Backups to keep", "Number of most recent successful backups retained, whatever the frequency (proposed default, not a user decision).",
               "int", 14, "storage", min=1, max=365, effect="Older backups beyond this count are pruned; the newest verified backup is never pruned.",
               help="backup-restore#retention"),
    SettingDef("backup.include_keys", "Include encryption key in backup",
               "Include the integration-secret encryption key so restores can decrypt SMTP/Telegram/email credentials. Protect the backup share accordingly.",
               "bool", True, "storage", help="backup-restore#keys"),
    SettingDef("audit.retention_days", "Audit log retention (days)", "Audit events older than this are deleted. 0 keeps forever.",
               "int", 730, "activity", min=0, max=36500, help="settings#activity"),
    # ---- Security & access
    SettingDef("security.login_audit_retention_days", "Login audit retention (days)",
               "Sign-in records older than this are deleted by the nightly maintenance. 0 keeps them forever.",
               "int", 365, "security", min=0, max=3650, effect="Applies at the next nightly maintenance run.",
               help="security-access#login-audit"),
    SettingDef("security.escalation_failures", "Failed sign-ins before automatic block",
               "Failed sign-ins from one public address within an hour that add a temporary automatic block (0 disables). LAN addresses are never blocked.",
               "int", 20, "security", min=0, max=1000, help="security-access#login-protection"),
    SettingDef("security.escalation_minutes", "Automatic block duration (minutes)",
               "How long an address stays blocked after too many failed sign-ins.", "int", 60, "security", min=5, max=10080,
               help="security-access#login-protection"),
    SettingDef("geoip.account_id", "MaxMind account ID", "Free GeoLite2 account used to download the country database.",
               "str", "", "security", max=20, validator=_validate_plain, help="security-access#geoip", example="123456"),
    SettingDef("geoip.license_key", "MaxMind license key", "Stored encrypted and never shown again. Sent only to MaxMind when downloading.",
               "secret", "", "security", help="security-access#geoip"),
    SettingDef("geoip.edition", "GeoIP database edition", "Country is enough for access control; City adds approximate cities to reports.",
               "choice", "GeoLite2-Country", "security", choices=("GeoLite2-Country", "GeoLite2-City"), help="security-access#geoip"),
    SettingDef("geoip.auto_update", "Update GeoIP weekly", "Download a fresh database every Wednesday night when credentials are set. A failed update keeps the current database.",
               "bool", True, "security", depends_on=("geoip.license_key",), help="security-access#geoip"),
    SettingDef("goaccess.enabled", "Traffic analytics (GoAccess)",
               "Build hourly traffic reports from the access log for Activity & health → Traffic analytics. Uses GoAccess when installed, otherwise a built-in summary.",
               "bool", False, "security", effect="Reports refresh hourly; nothing is exposed publicly.", help="security-access#goaccess"),
    SettingDef("alerts.failed_logins", "Alert: repeated failed sign-ins", "Notify administrators about repeated failures and automatic blocks.",
               "bool", True, "security", help="security-access#alerts"),
    SettingDef("alerts.new_country", "Alert: sign-in from a new country", "Notify the person and administrators when an account signs in from a country it never used before.",
               "bool", True, "security", help="security-access#alerts"),
    SettingDef("alerts.new_ip", "Alert: sign-in from a new address", "Notify the person and administrators about sign-ins from a new IP address (can be frequent on mobile networks).",
               "bool", False, "security", help="security-access#alerts"),
    SettingDef("alerts.policy_exception", "Alert: sign-in via temporary access", "Notify administrators when a sign-in was only possible because of a temporary travel exception.",
               "bool", True, "security", help="security-access#alerts"),
    SettingDef("alerts.policy_changes", "Alert: access policy changes", "Notify administrators when the country policy, trusted/blocked IPs or temporary access change or expire.",
               "bool", True, "security", help="security-access#alerts"),
    SettingDef("alerts.health", "Alert: GeoIP/GoAccess problems", "Notify administrators when a GeoIP update or traffic report fails.",
               "bool", True, "security", help="security-access#alerts"),
    SettingDef("alerts.account_security", "Alert: account security changes",
               "Notify the person (and administrators for admin actions) about passkeys, authenticator app, recovery codes and passwordless sign-in changes.",
               "bool", True, "security", help="security-access#alerts"),
    # ---- Local AI (optional; never required for normal document management)
    SettingDef("ai.enabled", "Local AI enabled",
               "Master switch for all AI features. Off by default; uploads, OCR, search and reminders never depend on it.",
               "bool", False, "ai", effect="Turning it off stops new AI jobs immediately; existing suggestions stay until reviewed.",
               help="local-ai#enable"),
    SettingDef("ai.ocr_assist", "OCR assist", "After OCR, ask the AI to suggest title, dates and document number for review.",
               "bool", True, "ai", depends_on=("ai.enabled",), help="local-ai#ocr-assist"),
    SettingDef("ai.smart_organization", "Smart organisation", "Suggest document type, issuer, tags and folder for review.",
               "bool", True, "ai", depends_on=("ai.enabled",), help="local-ai#smart-organization"),
    SettingDef("ai.semantic_search", "Semantic search", "Create embeddings of document text so searches can match meaning, not only words.",
               "bool", False, "ai", depends_on=("ai.enabled",), effect="Use 'Rebuild semantic index' after enabling it.",
               help="local-ai#semantic-search"),
    SettingDef("ai.assistant", "Document assistant", "Answer questions using only documents the asking person may open.",
               "bool", True, "ai", depends_on=("ai.enabled",), help="local-ai#assistant"),
    SettingDef("ai.allowed_users", "Who may use AI", "Everyone (each person only on their own permitted documents) or administrators only.",
               "choice", "everyone", "ai", choices=("everyone", "admins"), help="local-ai#permissions"),
    SettingDef("ai.auto_analyze", "Analyse new uploads automatically", "Queue OCR assist / smart organisation / embeddings after each upload is processed.",
               "bool", True, "ai", depends_on=("ai.enabled",), help="local-ai#ocr-assist"),
    SettingDef("ai.max_parallel", "Parallel AI jobs", "AI jobs running at the same time. Keep 1 on a 2-CPU container so documents are never delayed.",
               "int", 1, "ai", min=1, max=4, help="local-ai#resources"),
    SettingDef("ai.debug_logging", "AI diagnostic logging", "Log request and response sizes (never their content) for troubleshooting.",
               "bool", False, "ai", help="local-ai#troubleshooting"),
    # ---- Overview
    SettingDef("overview.holiday_countries", "Holiday countries",
               "Countries whose public holidays appear in the calendar and the Upcoming holidays widget. Holiday dates "
               "come from the bundled holidays library; Islamic dates are calculated and shown as provisional until "
               "you confirm them below.",
               "country_list", ["SA", "IN"], "overview", effect="Applies to everyone's Overview immediately.",
               help="overview#holidays", example="SA, IN"),
    SettingDef("overview.hijri_adjust", "Hijri date adjustment (days)",
               "The Hijri date follows the Umm al-Qura calendar. If the local moon sighting differs, shift it by up to two days.",
               "int", 0, "overview", min=-2, max=2, help="overview#hijri"),
    SettingDef("weather.enabled", "Weather widget", "Fetch the weather for the city each person chooses. The provider "
               "only receives the city coordinates, never documents or names. Off by default.",
               "bool", False, "overview", help="overview#weather"),
    SettingDef("weather.provider", "Weather provider", "Service used for forecasts and city search.", "choice",
               "open_meteo", "overview", choices=("open_meteo",), depends_on=("weather.enabled",),
               choice_labels={"open_meteo": "Open-Meteo (no account needed)"}, help="overview#weather"),
    SettingDef("weather.base_url", "Forecast address", "Forecast API address. Change it only for a commercial plan or a self-hosted mirror.",
               "url", "https://api.open-meteo.com/v1/forecast", "overview", depends_on=("weather.enabled",), max=300,
               help="overview#weather"),
    SettingDef("weather.geocoding_url", "City search address", "Geocoding API used when someone searches for a city.",
               "url", "https://geocoding-api.open-meteo.com/v1/search", "overview", depends_on=("weather.enabled",), max=300,
               help="overview#weather"),
    SettingDef("weather.api_key", "Weather API key", "Only needed for a commercial plan. Stored encrypted and never shown again.",
               "secret", "", "overview", depends_on=("weather.enabled",), help="overview#weather"),
    SettingDef("weather.cache_minutes", "Weather cache (minutes)", "How long a forecast is reused before the provider is asked again.",
               "int", 30, "overview", min=10, max=360, depends_on=("weather.enabled",), help="overview#weather"),
    SettingDef("weather.units", "Temperature units", "Units for every account.", "choice", "celsius", "overview",
               choices=("celsius", "fahrenheit"), choice_labels={"celsius": "Celsius (°C)", "fahrenheit": "Fahrenheit (°F)"},
               depends_on=("weather.enabled",), help="overview#weather"),
    SettingDef("weather.default_city", "Default city", "City shown to people who have not chosen their own.", "json", None,
               "overview_hidden", depends_on=("weather.enabled",), help="overview#weather"),
    # ---- Sign-in page
    SettingDef("login.design", "Sign-in page design",
               "Wallpaper on the left of the sign-in page. Sign-in works the same with every design.", "choice", "minimal",
               "login", choices=("minimal", "nature", "travel", "family", "neutral", "custom"),
               choice_labels={"minimal": "Minimal", "nature": "Nature", "travel": "Travel", "family": "Family",
                              "neutral": "Neutral", "custom": "Custom wallpaper"}, help="login-designs#presets"),
    SettingDef("login.title", "Sign-in title", "Heading on the sign-in page.", "str",
               "Personal Documents Management System", "login", max=80, help="login-designs#branding"),
    SettingDef("login.tagline", "Tagline", "Short line under the title. Leave empty to hide it.", "str",
               "Your family documents, safely in one place.", "login", max=120, help="login-designs#branding"),
    SettingDef("login.overlay", "Wallpaper overlay (%)", "Lightens the wallpaper so text stays readable.", "int", 0,
               "login", min=0, max=80, help="login-designs#custom"),
    SettingDef("login.position", "Wallpaper position", "Which part of a custom wallpaper stays visible when it is cropped.",
               "choice", "center", "login", choices=("center", "top", "bottom", "left", "right"),
               choice_labels={"center": "Centre", "top": "Top", "bottom": "Bottom", "left": "Left", "right": "Right"},
               help="login-designs#custom"),
    SettingDef("login.wallpaper_file", "Custom wallpaper file", "Set by uploading a wallpaper.", "str", "", "login_hidden",
               max=80, help="login-designs#custom"),
    SettingDef("login.logo_file", "Logo file", "Set by uploading a logo.", "str", "", "login_hidden", max=80,
               help="login-designs#branding"),
    # ---- Antivirus (ClamAV)
    SettingDef("antivirus.enabled", "Antivirus scanning (ClamAV)",
               "Scan every new file in the background with the local ClamAV daemon. Files stay usable while they are scanned; "
               "a detected threat is quarantined.", "bool", True, "antivirus", editable_by=ADMIN, help="antivirus#overview"),
    SettingDef("antivirus.socket", "ClamAV socket", "Local Unix socket of clamd. ClamAV is never contacted over the network.",
               "path", "/run/clamav/clamd.ctl", "antivirus", depends_on=("antivirus.enabled",), help="antivirus#install",
               example="/run/clamav/clamd.ctl"),
    SettingDef("antivirus.max_scan_mb", "Maximum scan size (MB)",
               "Larger files are stored normally but marked Not scanned — size limit exceeded. Above 200 MB a scan can use "
               "a lot of memory on a 4 GB server.", "int", 50, "antivirus", min=1, max=1024, editable_by=ADMIN,
               depends_on=("antivirus.enabled",), help="antivirus#size"),
    SettingDef("antivirus.scan_frequency", "Re-scan the whole library", "Scheduled re-scan of every stored file with the newest signatures.",
               "choice", "disabled", "antivirus", choices=("disabled", "daily", "weekly", "monthly"), editable_by=ADMIN,
               choice_labels={"disabled": "Disabled", "daily": "Daily", "weekly": "Weekly", "monthly": "Monthly"},
               depends_on=("antivirus.enabled",), help="antivirus#schedule"),
    SettingDef("antivirus.scan_time", "Re-scan time", "Local time (installation timezone) when a scheduled re-scan starts.",
               "time", "02:30", "antivirus", editable_by=ADMIN, depends_on=("antivirus.enabled",), help="antivirus#schedule"),
    SettingDef("antivirus.scan_weekday", "Re-scan day of week", "Used by the weekly schedule.", "choice", "sun", "antivirus",
               choices=("mon", "tue", "wed", "thu", "fri", "sat", "sun"), editable_by=ADMIN,
               choice_labels={"mon": "Monday", "tue": "Tuesday", "wed": "Wednesday", "thu": "Thursday", "fri": "Friday",
                              "sat": "Saturday", "sun": "Sunday"}, help="antivirus#schedule"),
    SettingDef("antivirus.scan_month_day", "Re-scan day of month", "Used by the monthly schedule; 29–31 run on the last day of shorter months.",
               "int", 1, "antivirus", min=1, max=31, editable_by=ADMIN, help="antivirus#schedule"),
    SettingDef("antivirus.stale_days", "Definitions out of date after (days)",
               "Signatures older than this show a warning and alert administrators.", "int", 2, "antivirus", min=1, max=30,
               editable_by=ADMIN, help="antivirus#signatures"),
    SettingDef("antivirus.critical_stale_days", "Definitions critically stale after (days)",
               "Signatures older than this put Security Health at risk.", "int", 7, "antivirus", min=2, max=90,
               editable_by=ADMIN, help="antivirus#signatures"),
    # ---- External identity provider (authentik)
    SettingDef("authentik.enabled", "Sign in with authentik", "Offer sign-in through your authentik server (OpenID Connect). "
               "Local sign-in always stays available.", "bool", False, "identity", help="authentik#setup"),
    SettingDef("authentik.issuer", "Issuer / discovery URL",
               "The provider's issuer URL; /.well-known/openid-configuration is read from it.", "url", "", "identity", max=300,
               depends_on=("authentik.enabled",), help="authentik#setup",
               example="https://auth.example.com/application/o/personal-dm/"),
    SettingDef("authentik.client_id", "Client ID", "From the authentik OAuth2/OpenID provider.", "str", "", "identity", max=200,
               depends_on=("authentik.enabled",), help="authentik#setup"),
    SettingDef("authentik.client_secret", "Client secret", "Stored encrypted and never shown again.", "secret", "", "identity",
               depends_on=("authentik.enabled",), help="authentik#setup"),
    SettingDef("authentik.scopes", "Scopes", "Requested scopes; openid is always included.", "str", "openid profile email",
               "identity", max=200, depends_on=("authentik.enabled",), help="authentik#setup"),
    SettingDef("authentik.button_label", "Button label", "Text of the sign-in button.", "str", "Sign in with authentik",
               "identity", max=60, depends_on=("authentik.enabled",), help="authentik#button"),
    SettingDef("authentik.show_logo", "Show authentik logo", "Show the authentik mark on the sign-in button.", "bool", True,
               "identity", depends_on=("authentik.enabled",), help="authentik#button"),
    SettingDef("authentik.provisioning", "Account provisioning",
               "Existing accounts only: people link authentik from their own account first. Automatic: unknown authentik "
               "users get a new member account (never the main administrator).", "choice", "existing_only", "identity",
               choices=("existing_only", "auto"), depends_on=("authentik.enabled",),
               choice_labels={"existing_only": "Existing Personal DM accounts only (default)", "auto": "Create accounts automatically"},
               help="authentik#provisioning"),
    SettingDef("authentik.username_claim", "Username claim", "Claim used as the username of automatically created accounts.",
               "str", "preferred_username", "identity", max=60, validator=_validate_plain, help="authentik#claims"),
    SettingDef("authentik.name_claim", "Display name claim", "Claim used as the display name of new accounts.", "str", "name",
               "identity", max=60, validator=_validate_plain, help="authentik#claims"),
    SettingDef("authentik.email_claim", "Email claim", "Shown on the link; never used to link accounts automatically.",
               "str", "email", "identity", max=60, validator=_validate_plain, help="authentik#claims"),
    SettingDef("authentik.groups_claim", "Groups claim", "Claim that lists the person's authentik groups.", "str", "groups",
               "identity", max=60, validator=_validate_plain, help="authentik#groups"),
    SettingDef("authentik.group_mapping_enabled", "Map authentik groups to roles",
               "Off by default. Groups only set the Member/Administrator role; document and folder access never comes from groups.",
               "bool", False, "identity", depends_on=("authentik.enabled",), help="authentik#groups"),
    SettingDef("authentik.group_mapping", "Group-to-role mapping", "authentik group name → Member or Administrator.", "json", {},
               "identity_hidden", validator=_validate_group_mapping, help="authentik#groups", example='{"pdm-admins": "administrator"}'),
    # ---- Security center
    SettingDef("security.deployment", "Deployment exposure",
               "Internet-facing deployments must pass the HTTPS checks to be reported as Internet Ready.", "choice", "lan",
               "security_center", choices=("lan", "internet"),
               choice_labels={"lan": "LAN only (home network / VPN)", "internet": "Published on the Internet"},
               help="security-center#internet-ready"),
    SettingDef("security.log_retention_days", "Security record retention (days)",
               "Antivirus events, security tests, OS update runs, authentik and security alerts are kept at least one year.",
               "int", 365, "security_center", min=365, max=3650, help="security-center#retention"),
    SettingDef("storage.warn_percent", "Storage warning at (% used)", "Show a warning and notify administrators.", "int", 80,
               "security_center", min=50, max=99, editable_by=ADMIN, help="security-center#storage"),
    SettingDef("storage.critical_percent", "Storage critical at (% used)", "Critical storage alert.", "int", 90, "security_center",
               min=51, max=100, editable_by=ADMIN, help="security-center#storage"),
    # ---- Per-user
    SettingDef("me.theme", "Theme", "Colour theme for your account on every device.", "choice", "green", "appearance",
               scope=USER, editable_by=SELF, choices=THEMES, effect="Applies immediately on all your devices.",
               help="themes#choose"),
    SettingDef("me.layout", "Default document layout", "Three-panel browser or full-page viewer.", "choice",
               "three_panel", "appearance", scope=USER, editable_by=SELF, choices=LAYOUTS, help="themes#layout"),
    SettingDef("me.doc_view", "Folder view", "How documents are shown in folders: list, thumbnails or details.", "choice",
               "list", "appearance", scope=USER, editable_by=SELF, choices=("list", "thumbnails", "details"),
               effect="Applies on all your devices.", help="getting-started#views"),
    SettingDef("me.doc_sort", "Sort documents by", "Order of documents in folders.", "choice", "-added", "appearance",
               scope=USER, editable_by=SELF, choices=("-added", "added", "name", "-name", "size", "-size", "expiry", "-expiry", "type", "-type"),
               effect="Applies on all your devices.", help="getting-started#views"),
    SettingDef("me.notification_prefs", "My notifications", "Which optional notifications you receive, per channel.",
               "event_matrix", {}, "my_notifications", scope=USER, editable_by=SELF, help="expiry-rules#optional"),
    SettingDef("me.channels", "My notification channels", "Channels you want reminders on. Required channels stay on.",
               "channel_list", None, "my_notifications", scope=USER, editable_by=SELF, help="expiry-rules#channels"),
    SettingDef("me.push_preview", "Push notification detail",
               "What your phone or computer may show on the lock screen. Minimal: only that something needs attention. "
               "Standard: the alert title and a short summary without names. Detailed: also document names. Document numbers and text are never shown.",
               "choice", "standard", "my_notifications", scope=USER, editable_by=SELF, choices=("minimal", "standard", "detailed"),
               help="notifications#push"),
    SettingDef("me.event_alerts", "Other alerts by email/Telegram",
               "Also send access, import and (for administrators) backup and integrity alerts to your email/Telegram channels. They always appear in the in-app feed.",
               "bool", True, "my_notifications", scope=USER, editable_by=SELF, help="expiry-rules#other-alerts"),
    SettingDef("me.dashboard_widgets", "Overview widgets",
               "Choose what your Overview shows and in which order. Saved to your account, so every device shows the same. "
               "Use Customize Overview for sizes and styles.",
               "widget_list", DEFAULT_WIDGETS, "appearance", scope=USER, editable_by=SELF, choices=list(WIDGETS),
               effect="Applies on all your devices.", help="overview#customize"),
    SettingDef("me.overview_layout", "Overview layout", "Size, style and options of each Overview widget.", "overview_layout",
               {}, "appearance_hidden", scope=USER, editable_by=SELF, help="overview#customize"),
    SettingDef("me.weather_city", "Weather city", "City for your weather widget.", "json", None, "appearance_hidden",
               scope=USER, editable_by=SELF, help="overview#weather"),
]

BY_KEY = {s.key: s for s in SETTINGS}


def coerce(defn: SettingDef, value: Any) -> Any:
    t = defn.type
    if value is None and t in ("channel_list",) and defn.scope == USER:
        return None
    if t == "bool":
        if not isinstance(value, bool):
            raise SettingError("Must be true or false.")
    elif t == "int":
        try:
            value = int(value)
        except (TypeError, ValueError):
            raise SettingError("Must be a whole number.")
        if defn.min is not None and value < defn.min:
            raise SettingError(f"Must be at least {defn.min}.")
        if defn.max is not None and value > defn.max:
            raise SettingError(f"Must be at most {defn.max}.")
    elif t in ("str", "secret", "path", "email", "url"):
        if not isinstance(value, str):
            raise SettingError("Must be text.")
        value = value.strip() if t != "secret" else value
        if defn.max is not None and len(value) > defn.max:
            raise SettingError(f"Must be at most {defn.max} characters.")
        if t == "email" and value and not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", value):
            raise SettingError("Enter a valid email address.")
        if t == "path" and value and not value.startswith("/"):
            raise SettingError("Enter an absolute path such as /mnt/nas-backup.")
    elif t == "choice":
        if value not in defn.choices:
            raise SettingError(f"Choose one of: {', '.join(defn.choices)}.")
    elif t == "choice_list":
        if not isinstance(value, list) or any(v not in defn.choices for v in value):
            raise SettingError(f"Choose from: {', '.join(defn.choices)}.")
        value = [c for c in defn.choices if c in value]
    elif t == "int_list":
        if isinstance(value, str):
            value = [v for v in re.split(r"[,\s]+", value) if v]
        try:
            value = [int(v) for v in value]
        except (TypeError, ValueError):
            raise SettingError("Enter whole numbers separated by commas.")
    elif t == "channel_list":
        if not isinstance(value, list) or any(v not in CHANNELS for v in value):
            raise SettingError(f"Channels must be from: {', '.join(CHANNELS)}.")
        value = [c for c in CHANNELS if c in value]
    elif t == "event_list":
        if not isinstance(value, list) or any(v not in NOTIFY_EVENTS for v in value):
            raise SettingError("Unknown notification event.")
        if defn.key == "notifications.critical_events":  # some security events can never be made optional
            value = list(value) + [k for k, e in NOTIFY_EVENTS.items() if e.always_critical]
        value = [k for k in NOTIFY_EVENTS if k in value]
    elif t == "event_matrix":
        from apps.notify.catalog import coerce_prefs

        value = coerce_prefs(value)
    elif t == "widget_list":
        if not isinstance(value, (list, str)) or (isinstance(value, list) and any(v not in WIDGETS for v in value)):
            raise SettingError(f"Widgets must be from: {', '.join(WIDGETS)}.")
        value = normalize_widgets(value)
    elif t == "country_list":
        from .overview import country_names

        names = country_names()
        if isinstance(value, str):
            value = [v for v in re.split(r"[,\s]+", value) if v]
        if not isinstance(value, list) or any(not isinstance(v, str) or v.upper() not in names for v in value):
            raise SettingError("Choose countries from the list.")
        value = list(dict.fromkeys(v.upper() for v in value))
        if len(value) > 12:
            raise SettingError("Choose at most 12 countries.")
    elif t == "overview_layout":
        from .overview import normalize_layout

        value = normalize_layout(value)
    elif t == "json" and defn.key in ("me.weather_city", "weather.default_city"):
        from .overview import normalize_city

        value = normalize_city(value)
    elif t == "time":
        if not isinstance(value, str) or (value and not re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", value)):
            raise SettingError("Use 24-hour HH:MM, for example 08:00.")
    elif t == "timezone":
        try:
            zoneinfo.ZoneInfo(value)
        except Exception:
            raise SettingError("Unknown timezone. Use a name like Asia/Riyadh.")
    if defn.validator:
        defn.validator(value)
    if t == "int_list":
        value = sorted(value, reverse=True)
    return value
