# Generated by Django 5.2.17 on 2026-10-05 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("reason", models.CharField(max_length=30)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("day", "reason", "country")},
            },
        ),
        migrations.CreateModel(
            name="GeoPolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("off", "off"),
                            ("blocklist", "blocklist"),
                            ("allowlist", "allowlist"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                (
                    "unknown_action",
                    models.CharField(
                        default="allow",
                        help_text="allow|deny when the country cannot be determined",
                        max_length=5,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "previous",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot before the last change, for rollback",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IPRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[("trusted", "trusted"), ("blocked", "blocked")],
                        db_index=True,
                        max_length=7,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "automatic",
                    models.BooleanField(
                        default=False, help_text="Created by failed-login escalation"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "cidr"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryCountryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiry_notified", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ends_at"],
            },
        ),
        migrations.CreateModel(
            name="CountryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                (
                    "kind",
                    models.CharField(
                        choices=[("allow", "allow"), ("block", "block")], max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "country"],
                "unique_together": {("country", "kind")},
            },
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username as typed (for failures with no account)",
                        max_length=150,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("failure", "failure"),
                            ("denied", "denied"),
                            ("logout", "logout"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("method", models.CharField(blank=True, db_index=True, max_length=40)),
                ("reason", models.CharField(blank=True, max_length=40)),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("country", models.CharField(blank=True, db_index=True, max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=80)),
                ("browser", models.CharField(blank=True, max_length=40)),
                ("os", models.CharField(blank=True, max_length=40)),
                ("device", models.CharField(blank=True, max_length=10)),
                (
                    "correlation",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("totp_used", models.BooleanField(default=False)),
                ("passkey_used", models.BooleanField(default=False)),
                ("oidc_used", models.BooleanField(default=False)),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-at"], name="security_lo_user_id_20d828_idx"
                    ),
                    models.Index(
                        fields=["result", "-at"], name="security_lo_result_77f333_idx"
                    ),
                ],
            },
        ),
    ]
