# Generated by Django 5.2.17 on 2026-10-07 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthState",
            fields=[
                (
                    "key",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AvScanRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kind", models.CharField(default="manual", max_length=12)),
                ("scope", models.CharField(default="library", max_length=12)),
                ("folder_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="running", max_length=12),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total", models.IntegerField(default=0)),
                ("done", models.IntegerField(default=0)),
                (
                    "cursor",
                    models.CharField(
                        blank=True,
                        help_text="Last processed version id (resume point)",
                        max_length=64,
                    ),
                ),
                ("counts", models.JSONField(blank=True, default=dict)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
