# Generated by Django 5.2.17 on 2026-10-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_antivirus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OsUpdateRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=20)),
                ("request_id", models.CharField(blank=True, max_length=40)),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="requested", max_length=12)),
                ("backup_status", models.CharField(blank=True, max_length=12)),
                ("backup_detail", models.CharField(blank=True, max_length=300)),
                ("backup_override", models.BooleanField(default=False)),
                ("override_reason", models.CharField(blank=True, max_length=300)),
                ("packages", models.JSONField(blank=True, default=list)),
                ("log_name", models.CharField(blank=True, max_length=80)),
                ("reboot_required", models.BooleanField(null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityTestRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=10)),
                ("deployment", models.CharField(default="lan", max_length=10)),
                ("findings", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
