# Generated by Django 5.2.17 on 2026-10-03 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("host", models.CharField(max_length=200)),
                ("port", models.IntegerField(default=993)),
                ("security", models.CharField(default="ssl", max_length=10)),
                ("username", models.CharField(max_length=200)),
                ("password_enc", models.TextField()),
                ("mailbox", models.CharField(default="INBOX", max_length=200)),
                ("poll_minutes", models.IntegerField(default=30)),
                ("enabled", models.BooleanField(default=True)),
                ("disabled_by_admin", models.BooleanField(default=False)),
                ("last_poll_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("uidvalidity", models.CharField(blank=True, max_length=40)),
                ("last_uid", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("sender_contains", models.CharField(blank=True, max_length=200)),
                ("subject_contains", models.CharField(blank=True, max_length=200)),
                (
                    "extensions",
                    models.CharField(default="pdf,jpg,jpeg,png", max_length=200),
                ),
                ("max_mb", models.IntegerField(default=25)),
                ("enabled", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="mailimport.emailaccount",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="library.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImportedAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uidvalidity", models.CharField(max_length=40)),
                ("uid", models.BigIntegerField()),
                ("part_index", models.IntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("status", models.CharField(default="done", max_length=10)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported",
                        to="mailimport.emailaccount",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="library.document",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mailimport.emailrule",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "uidvalidity", "uid", "part_index")},
            },
        ),
    ]
