# Generated by Django 5.2.17 on 2026-10-05 10:41

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0003_pdfa_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            (
                                "openai",
                                "OpenAI-compatible (LM Studio, llama.cpp, vLLM, LocalAI)",
                            ),
                            ("ollama", "Ollama"),
                        ],
                        default="openai",
                        max_length=10,
                    ),
                ),
                ("base_url", models.CharField(max_length=300)),
                ("api_key_enc", models.TextField(blank=True)),
                ("text_model", models.CharField(blank=True, max_length=200)),
                ("vision_model", models.CharField(blank=True, max_length=200)),
                ("embedding_model", models.CharField(blank=True, max_length=200)),
                ("timeout_seconds", models.PositiveIntegerField(default=60)),
                ("max_input_chars", models.PositiveIntegerField(default=12000)),
                ("max_output_tokens", models.PositiveIntegerField(default=800)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("local", "Local only (this server)"),
                            ("lan", "Private LAN"),
                            ("external", "External endpoint"),
                        ],
                        default="lan",
                        max_length=10,
                    ),
                ),
                ("external_acknowledged", models.BooleanField(default=False)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Features this profile may serve (empty = all enabled)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=12)),
                ("model", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=10),
                ),
                ("error_category", models.CharField(blank=True, max_length=30)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("retryable", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="library.document",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="ai.aiprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=40)),
                ("value", models.JSONField()),
                ("display", models.CharField(max_length=300)),
                ("current", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="library.document",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="ai.aijob",
                    ),
                ),
            ],
            options={
                "ordering": ["field", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idx", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chunks",
                        to="library.document",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="library.documentversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["status", "-created_at"], name="ai_aijob_status_bed593_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("version", "idx", "model")},
        ),
    ]
