# Generated by Django 5.2.17 on 2026-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_name",
            field=models.CharField(
                blank=True,
                help_text="Random file stem in <data>/profile-photos (private)",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
