# Generated by Django 5.2.17 on 2026-10-05 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passwordless_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Person opted in to passwordless passkey sign-in",
            ),
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        help_text="base64url credential id",
                        max_length=1400,
                        unique=True,
                    ),
                ),
                ("public_key", models.BinaryField()),
                ("sign_count", models.BigIntegerField(default=0)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("aaguid", models.CharField(blank=True, max_length=40)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("backed_up", models.BooleanField(default=False)),
                (
                    "discoverable",
                    models.BooleanField(
                        default=False,
                        help_text="Resident key: usable for passwordless sign-in",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
