# Generated by Django 5.2.17 on 2026-10-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Administrator: security and operations area (antivirus, security tests, storage health). The main administrator always has these rights.",
            ),
        ),
    ]
