# Generated by Django 5.2.17 on 2026-10-07 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_administrator_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="authentik", max_length=30)),
                ("issuer", models.CharField(max_length=300)),
                ("subject", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("groups", models.JSONField(blank=True, default=list)),
                (
                    "provisioned",
                    models.BooleanField(
                        default=False,
                        help_text="Account was created automatically on first sign-in",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("issuer", "subject"), ("provider", "user")},
            },
        ),
    ]
