# Generated by Django 5.2.17 on 2026-10-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_passkey_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="offline_allowed",
            field=models.BooleanField(
                default=True,
                help_text="May keep offline copies on their devices (set by the administrator)",
            ),
        ),
    ]
