# Generated by Django 5.2.17 on 2026-10-07 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

KIND_MAP = {  # older in-app rows: kind -> (category, severity, svg icon)
    "expiry": ("expiry", "warning", "calendar"), "access": ("sharing", "info", "users"), "import": ("documents", "success", "folder"),
    "backup": ("system", "critical", "db"), "integrity": ("system", "critical", "db"), "processing": ("ocr", "info", "search"),
    "archive": ("documents", "info", "file"), "document": ("documents", "success", "upload"), "security": ("security", "warning", "shield"),
    "security.operations": ("system", "warning", "settings"), "antivirus.threat": ("security", "critical", "alert"),
    "antivirus.unavailable": ("security", "critical", "alert"), "antivirus.definitions": ("security", "warning", "shield"),
    "antivirus.released": ("security", "critical", "shield"),
}


def classify_existing(apps, schema_editor):
    """Give earlier in-app notifications a category, severity and icon. Titles, bodies, links and read state stay."""
    Notification = apps.get_model("notify", "Notification")
    for kind, (cat, sev, icon) in KIND_MAP.items():
        Notification.objects.filter(kind=kind, category="").update(category=cat, severity=sev, icon=icon)
    Notification.objects.filter(category="").update(category="system", icon="bell")


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0009_document_type_templates"),
        ("notify", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="details and actions of the card"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="severity",
            field=models.CharField(db_index=True, default="info", max_length=10),
        ),
        migrations.AddField(
            model_name="notification",
            name="summary",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="event",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="provider_ref",
            field=models.CharField(
                blank=True,
                help_text="Provider message id when reported",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="severity",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=1000, unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=60)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Browser / device summary", max_length=120
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpirySnooze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("until", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="library.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "document")},
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=60)),
                ("channel", models.CharField(blank=True, max_length=16)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("heading", models.CharField(blank=True, max_length=200)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("icon", models.CharField(blank=True, max_length=30)),
                ("severity", models.CharField(blank=True, max_length=10)),
                ("action_labels", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "channel")},
            },
        ),
        migrations.RunPython(classify_existing, migrations.RunPython.noop),
]
