# Generated by Django 5.2.17 on 2026-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_rich_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Header name in email (default: the application name)",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="footer",
            field=models.CharField(
                blank=True, help_text="Footer / help text", max_length=300
            ),
        ),
    ]
